services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "rahul@dkfd48"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "2g"
        reservations:
          cpus: "0.5"
          memory: "1g"
    networks:
      - vaani-net

networks:
  vaani-net:
    external: true
