services:
  redisconnect:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "8001:8001"
      - "6379:6379"
    volumes:
      - ./redis-data/redisinsight:/db
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - vaani-net

networks:
  vaani-net:
    external: true
